//! Provider-native raw message capture over the segmented market-data WAL.

use super::{
    BoundedMarketDataWalWriter, BoundedMarketDataWriterConfig, BoundedMarketDataWriterMetrics,
    MarketDataWalProducer, MarketDataWalRecord, MarketDataWalRecordInput, MarketDataWalRecordKind,
    MarketDataWalSequence, MarketDataWriterControlError, MarketDataWriterTryError, PersistResult,
    SegmentedMarketDataWalConfig,
};
use std::error::Error;
use std::fmt;

const RAW_CAPTURE_MAGIC: [u8; 4] = *b"OFRC";
const RAW_CAPTURE_VERSION: u16 = 1;
const RAW_CAPTURE_HEADER_LEN: usize = 56;

/// Source of the receive timestamp attached to a raw provider message.
#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Default)]
#[non_exhaustive]
pub enum RawCaptureTimestampSource {
    /// Timestamp provenance is unavailable or provider-specific.
    #[default]
    Unknown = 0,
    /// Timestamp was sampled by the userspace adapter.
    Userspace = 1,
    /// Timestamp was generated in the kernel receive path.
    KernelSoftware = 2,
    /// Timestamp was generated by supported network hardware.
    Hardware = 3,
}

impl RawCaptureTimestampSource {
    fn from_u8(value: u8) -> Option<Self> {
        match value {
            0 => Some(Self::Unknown),
            1 => Some(Self::Userspace),
            2 => Some(Self::KernelSoftware),
            3 => Some(Self::Hardware),
            _ => None,
        }
    }
}

/// Stable flags describing the provider-native payload representation.
#[repr(transparent)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Default)]
pub struct RawCaptureFlags(u8);

impl RawCaptureFlags {
    /// Payload bytes are compressed with a stream-configured codec.
    pub const COMPRESSED: Self = Self(1 << 0);
    /// Payload bytes are encrypted with a stream-configured key.
    pub const ENCRYPTED: Self = Self(1 << 1);
    /// Sensitive fields were redacted before capture.
    pub const REDACTED: Self = Self(1 << 2);
    /// Provider message was intentionally truncated before capture.
    pub const TRUNCATED: Self = Self(1 << 3);

    /// Creates an empty flag set.
    pub const fn empty() -> Self {
        Self(0)
    }

    /// Creates a flag set from raw bits, rejecting unknown bits.
    pub const fn from_bits(bits: u8) -> Option<Self> {
        if bits & !0x0f == 0 {
            Some(Self(bits))
        } else {
            None
        }
    }

    /// Returns raw flag bits.
    pub const fn bits(self) -> u8 {
        self.0
    }

    /// Returns whether every flag in `other` is set.
    pub const fn contains(self, other: Self) -> bool {
        self.0 & other.0 == other.0
    }

    /// Returns the union of two flag sets.
    pub const fn union(self, other: Self) -> Self {
        Self(self.0 | other.0)
    }
}

/// Fixed provider/session identity stored ahead of each native payload.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Default)]
#[non_exhaustive]
pub struct RawCaptureMetadata {
    /// Stable provider identifier selected by the host.
    pub provider_id: u32,
    /// Stable adapter-instance identifier selected by the host.
    pub adapter_id: u32,
    /// Connection or provider-session identifier.
    pub connection_id: u64,
    /// Subscription identifier, or zero when unavailable.
    pub subscription_id: u64,
    /// Stable venue identifier, or zero when unavailable.
    pub venue_id: u64,
    /// Stable provider-native instrument identifier, or zero when unavailable.
    pub instrument_id: u64,
    /// Provenance of the outer WAL receive timestamp.
    pub timestamp_source: RawCaptureTimestampSource,
    /// Payload representation and handling flags.
    pub flags: RawCaptureFlags,
}

/// Error returned while validating or decoding a raw-capture envelope.
#[derive(Debug, Clone, PartialEq, Eq)]
#[non_exhaustive]
pub enum RawCaptureDecodeError {
    /// WAL record is not a provider-native raw message.
    WrongRecordKind,
    /// Envelope is shorter than its fixed header.
    TruncatedHeader,
    /// Envelope magic does not identify Orderflow raw capture.
    InvalidMagic,
    /// Envelope schema version is unsupported.
    UnsupportedVersion(u16),
    /// Encoded header length is invalid.
    InvalidHeaderLength(u16),
    /// Timestamp source discriminant is unknown.
    InvalidTimestampSource(u8),
    /// Payload flags contain unknown bits.
    InvalidFlags(u8),
    /// Reserved header bytes are nonzero.
    NonzeroReservedBytes,
}

impl fmt::Display for RawCaptureDecodeError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::WrongRecordKind => formatter.write_str("WAL record is not raw provider capture"),
            Self::TruncatedHeader => formatter.write_str("raw capture header is truncated"),
            Self::InvalidMagic => formatter.write_str("raw capture magic is invalid"),
            Self::UnsupportedVersion(version) => {
                write!(formatter, "raw capture version {version} is unsupported")
            }
            Self::InvalidHeaderLength(length) => {
                write!(formatter, "raw capture header length {length} is invalid")
            }
            Self::InvalidTimestampSource(source) => {
                write!(
                    formatter,
                    "raw capture timestamp source {source} is invalid"
                )
            }
            Self::InvalidFlags(flags) => {
                write!(formatter, "raw capture flags {flags:#04x} are invalid")
            }
            Self::NonzeroReservedBytes => {
                formatter.write_str("raw capture reserved header bytes are nonzero")
            }
        }
    }
}

impl Error for RawCaptureDecodeError {}

/// Invalid pre-encoded capture input with its allocation preserved.
#[derive(Debug)]
pub struct RawCaptureInputError {
    error: RawCaptureDecodeError,
    encoded_payload: Vec<u8>,
}

impl RawCaptureInputError {
    /// Returns the envelope validation failure.
    pub const fn error(&self) -> &RawCaptureDecodeError {
        &self.error
    }

    /// Returns the rejected encoded allocation.
    pub fn encoded_payload(&self) -> &[u8] {
        &self.encoded_payload
    }

    /// Consumes the error and returns its cause and reusable allocation.
    pub fn into_parts(self) -> (RawCaptureDecodeError, Vec<u8>) {
        (self.error, self.encoded_payload)
    }
}

impl fmt::Display for RawCaptureInputError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        self.error.fmt(formatter)
    }
}

impl Error for RawCaptureInputError {
    fn source(&self) -> Option<&(dyn Error + 'static)> {
        Some(&self.error)
    }
}

/// Appends a fixed raw-capture envelope header to a caller-owned buffer.
///
/// The buffer is cleared first. A transport can then append provider bytes and
/// pass the allocation to [`RawCaptureRecordInput::from_encoded_payload`]
/// without another payload copy.
pub fn prepare_raw_capture_payload(metadata: RawCaptureMetadata, out: &mut Vec<u8>) {
    out.clear();
    out.reserve(RAW_CAPTURE_HEADER_LEN);
    out.extend_from_slice(&RAW_CAPTURE_MAGIC);
    out.extend_from_slice(&RAW_CAPTURE_VERSION.to_le_bytes());
    out.extend_from_slice(&(RAW_CAPTURE_HEADER_LEN as u16).to_le_bytes());
    out.extend_from_slice(&metadata.provider_id.to_le_bytes());
    out.extend_from_slice(&metadata.adapter_id.to_le_bytes());
    out.extend_from_slice(&metadata.connection_id.to_le_bytes());
    out.extend_from_slice(&metadata.subscription_id.to_le_bytes());
    out.extend_from_slice(&metadata.venue_id.to_le_bytes());
    out.extend_from_slice(&metadata.instrument_id.to_le_bytes());
    out.push(metadata.timestamp_source as u8);
    out.push(metadata.flags.bits());
    out.extend_from_slice(&[0; 6]);
    debug_assert_eq!(out.len(), RAW_CAPTURE_HEADER_LEN);
}

/// Encodes one raw-capture envelope into reusable caller-owned storage.
pub fn encode_raw_capture_payload_into(
    metadata: RawCaptureMetadata,
    provider_payload: &[u8],
    out: &mut Vec<u8>,
) {
    prepare_raw_capture_payload(metadata, out);
    out.extend_from_slice(provider_payload);
}

/// Owned provider-native record accepted by a bounded raw-capture producer.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct RawCaptureRecordInput {
    metadata: RawCaptureMetadata,
    inner: MarketDataWalRecordInput,
}

impl RawCaptureRecordInput {
    /// Copies provider bytes into a versioned capture envelope.
    pub fn copy_from_slice(
        metadata: RawCaptureMetadata,
        provider_sequence: u64,
        ts_exchange_ns: u64,
        ts_recv_ns: u64,
        provider_payload: &[u8],
    ) -> Self {
        let mut encoded = Vec::with_capacity(RAW_CAPTURE_HEADER_LEN + provider_payload.len());
        encode_raw_capture_payload_into(metadata, provider_payload, &mut encoded);
        Self::from_validated_parts(
            metadata,
            provider_sequence,
            ts_exchange_ns,
            ts_recv_ns,
            encoded,
        )
    }

    /// Consumes a pre-encoded envelope without copying its provider payload.
    ///
    /// # Errors
    /// Returns an error when the fixed envelope header is malformed.
    pub fn from_encoded_payload(
        provider_sequence: u64,
        ts_exchange_ns: u64,
        ts_recv_ns: u64,
        encoded_payload: Vec<u8>,
    ) -> Result<Self, RawCaptureInputError> {
        let metadata = match decode_metadata(&encoded_payload) {
            Ok(metadata) => metadata,
            Err(error) => {
                return Err(RawCaptureInputError {
                    error,
                    encoded_payload,
                });
            }
        };
        Ok(Self::from_validated_parts(
            metadata,
            provider_sequence,
            ts_exchange_ns,
            ts_recv_ns,
            encoded_payload,
        ))
    }

    fn from_validated_parts(
        metadata: RawCaptureMetadata,
        provider_sequence: u64,
        ts_exchange_ns: u64,
        ts_recv_ns: u64,
        encoded_payload: Vec<u8>,
    ) -> Self {
        Self {
            metadata,
            inner: MarketDataWalRecordInput::new(
                MarketDataWalRecordKind::RawProviderMessage,
                provider_sequence,
                0,
                ts_exchange_ns,
                ts_recv_ns,
                encoded_payload,
            ),
        }
    }

    /// Returns capture metadata.
    pub const fn metadata(&self) -> RawCaptureMetadata {
        self.metadata
    }

    /// Returns provider-native sequence, or zero when unavailable.
    pub const fn provider_sequence(&self) -> u64 {
        self.inner.provider_sequence()
    }

    /// Returns exchange timestamp in nanoseconds, or zero when unavailable.
    pub const fn ts_exchange_ns(&self) -> u64 {
        self.inner.ts_exchange_ns()
    }

    /// Returns receive timestamp in nanoseconds.
    pub const fn ts_recv_ns(&self) -> u64 {
        self.inner.ts_recv_ns()
    }

    /// Returns provider-native payload bytes without the capture envelope.
    pub fn provider_payload(&self) -> &[u8] {
        &self.inner.payload()[RAW_CAPTURE_HEADER_LEN..]
    }

    /// Returns encoded envelope bytes counted against writer queue limits.
    pub const fn encoded_len(&self) -> usize {
        self.inner.payload_len()
    }

    /// Consumes the record and returns its reusable encoded allocation.
    pub fn into_encoded_payload(self) -> Vec<u8> {
        self.inner.into_payload()
    }
}

/// Decoded provider-native capture record returned by replay tooling.
#[derive(Debug, Clone, PartialEq, Eq)]
#[non_exhaustive]
pub struct RawCaptureRecord {
    /// Globally ordered capture sequence assigned by the WAL.
    pub capture_sequence: MarketDataWalSequence,
    /// Provider/session identity and payload flags.
    pub metadata: RawCaptureMetadata,
    /// Provider-native sequence, or zero when unavailable.
    pub provider_sequence: u64,
    /// Exchange timestamp in nanoseconds, or zero when unavailable.
    pub ts_exchange_ns: u64,
    /// Local receive timestamp in nanoseconds.
    pub ts_recv_ns: u64,
    /// Provider-native message bytes.
    pub payload: Vec<u8>,
}

impl TryFrom<MarketDataWalRecord> for RawCaptureRecord {
    type Error = RawCaptureDecodeError;

    fn try_from(mut record: MarketDataWalRecord) -> Result<Self, Self::Error> {
        if record.kind != MarketDataWalRecordKind::RawProviderMessage {
            return Err(RawCaptureDecodeError::WrongRecordKind);
        }
        let metadata = decode_metadata(&record.payload)?;
        record.payload.drain(..RAW_CAPTURE_HEADER_LEN);
        Ok(Self {
            capture_sequence: record.sequence,
            metadata,
            provider_sequence: record.provider_sequence,
            ts_exchange_ns: record.ts_exchange_ns,
            ts_recv_ns: record.ts_recv_ns,
            payload: record.payload,
        })
    }
}

/// Nonblocking raw-capture rejection that returns the original record.
#[derive(Debug)]
#[non_exhaustive]
pub enum RawCaptureTryError {
    /// Record-count queue capacity is exhausted.
    Full(RawCaptureRecordInput),
    /// Aggregate queued-byte capacity is exhausted.
    BytesFull(RawCaptureRecordInput),
    /// Encoded capture exceeds the configured WAL payload limit.
    PayloadTooLarge(RawCaptureRecordInput),
    /// Capture writer no longer accepts records.
    Stopped(RawCaptureRecordInput),
}

impl RawCaptureTryError {
    /// Returns the rejected input for retry, alternate storage, or pooling.
    pub fn into_input(self) -> RawCaptureRecordInput {
        match self {
            Self::Full(input)
            | Self::BytesFull(input)
            | Self::PayloadTooLarge(input)
            | Self::Stopped(input) => input,
        }
    }

    fn from_writer(error: MarketDataWriterTryError, metadata: RawCaptureMetadata) -> Self {
        match error {
            MarketDataWriterTryError::Full(inner) => {
                Self::Full(RawCaptureRecordInput { metadata, inner })
            }
            MarketDataWriterTryError::BytesFull(inner) => {
                Self::BytesFull(RawCaptureRecordInput { metadata, inner })
            }
            MarketDataWriterTryError::PayloadTooLarge(inner) => {
                Self::PayloadTooLarge(RawCaptureRecordInput { metadata, inner })
            }
            MarketDataWriterTryError::Stopped(inner)
            | MarketDataWriterTryError::ReservedRecordKind(inner) => {
                Self::Stopped(RawCaptureRecordInput { metadata, inner })
            }
        }
    }
}

impl fmt::Display for RawCaptureTryError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        let message = match self {
            Self::Full(_) => "raw capture record queue is full",
            Self::BytesFull(_) => "raw capture payload-byte queue is full",
            Self::PayloadTooLarge(_) => "raw capture payload exceeds configured maximum",
            Self::Stopped(_) => "raw capture writer is stopped",
        };
        formatter.write_str(message)
    }
}

impl Error for RawCaptureTryError {}

/// Cloneable nonblocking producer for provider-native capture.
#[derive(Debug, Clone)]
pub struct RawCaptureProducer {
    inner: MarketDataWalProducer,
}

impl RawCaptureProducer {
    /// Attempts to enqueue an owned capture without waiting for queue space.
    pub fn try_capture_owned(
        &self,
        input: RawCaptureRecordInput,
    ) -> Result<(), RawCaptureTryError> {
        let metadata = input.metadata;
        self.inner
            .try_append_owned(input.inner)
            .map_err(|error| RawCaptureTryError::from_writer(error, metadata))
    }

    /// Copies and attempts to enqueue provider-native bytes.
    pub fn try_capture_copy(
        &self,
        metadata: RawCaptureMetadata,
        provider_sequence: u64,
        ts_exchange_ns: u64,
        ts_recv_ns: u64,
        provider_payload: &[u8],
    ) -> Result<(), RawCaptureTryError> {
        self.try_capture_owned(RawCaptureRecordInput::copy_from_slice(
            metadata,
            provider_sequence,
            ts_exchange_ns,
            ts_recv_ns,
            provider_payload,
        ))
    }

    /// Returns lock-free queue, write, sync, and failure metrics.
    pub fn metrics(&self) -> BoundedMarketDataWriterMetrics {
        self.inner.metrics()
    }

    /// Returns the latest persistence failure text, if any.
    pub fn last_error(&self) -> Option<String> {
        self.inner.last_error()
    }
}

/// Bounded provider-native capture writer backed by a segmented WAL.
#[derive(Debug)]
pub struct BoundedRawCaptureWriter {
    inner: BoundedMarketDataWalWriter,
}

impl BoundedRawCaptureWriter {
    /// Opens a capture root and starts its single-owner writer thread.
    ///
    /// # Errors
    /// Returns an error for invalid bounds, capture-root recovery failure, or
    /// writer-thread creation failure.
    pub fn start(
        wal_config: SegmentedMarketDataWalConfig,
        writer_config: BoundedMarketDataWriterConfig,
    ) -> PersistResult<Self> {
        Ok(Self {
            inner: BoundedMarketDataWalWriter::start(wal_config, writer_config)?,
        })
    }

    /// Returns a cloneable nonblocking capture producer.
    pub fn producer(&self) -> RawCaptureProducer {
        RawCaptureProducer {
            inner: self.inner.producer(),
        }
    }

    /// Attempts to enqueue an owned capture without waiting for queue space.
    pub fn try_capture_owned(
        &self,
        input: RawCaptureRecordInput,
    ) -> Result<(), RawCaptureTryError> {
        self.producer().try_capture_owned(input)
    }

    /// Waits for earlier captures and synchronizes the active segment.
    ///
    /// This blocking control-plane operation must not run on a feed hot path.
    pub fn flush(&self) -> Result<(), MarketDataWriterControlError> {
        self.inner.flush()
    }

    /// Returns lock-free queue, write, sync, and failure metrics.
    pub fn metrics(&self) -> BoundedMarketDataWriterMetrics {
        self.inner.metrics()
    }

    /// Returns the latest persistence failure text, if any.
    pub fn last_error(&self) -> Option<String> {
        self.inner.last_error()
    }

    /// Stops admission, drains captures, syncs, and joins the writer thread.
    pub fn shutdown(self) -> Result<BoundedMarketDataWriterMetrics, MarketDataWriterControlError> {
        self.inner.shutdown()
    }
}

fn decode_metadata(payload: &[u8]) -> Result<RawCaptureMetadata, RawCaptureDecodeError> {
    if payload.len() < RAW_CAPTURE_HEADER_LEN {
        return Err(RawCaptureDecodeError::TruncatedHeader);
    }
    if payload[..4] != RAW_CAPTURE_MAGIC {
        return Err(RawCaptureDecodeError::InvalidMagic);
    }
    let version = u16::from_le_bytes([payload[4], payload[5]]);
    if version != RAW_CAPTURE_VERSION {
        return Err(RawCaptureDecodeError::UnsupportedVersion(version));
    }
    let header_len = u16::from_le_bytes([payload[6], payload[7]]);
    if header_len as usize != RAW_CAPTURE_HEADER_LEN {
        return Err(RawCaptureDecodeError::InvalidHeaderLength(header_len));
    }
    let timestamp_source = RawCaptureTimestampSource::from_u8(payload[48])
        .ok_or(RawCaptureDecodeError::InvalidTimestampSource(payload[48]))?;
    let flags = RawCaptureFlags::from_bits(payload[49])
        .ok_or(RawCaptureDecodeError::InvalidFlags(payload[49]))?;
    if payload[50..56].iter().any(|byte| *byte != 0) {
        return Err(RawCaptureDecodeError::NonzeroReservedBytes);
    }
    Ok(RawCaptureMetadata {
        provider_id: read_u32(&payload[8..12]),
        adapter_id: read_u32(&payload[12..16]),
        connection_id: read_u64(&payload[16..24]),
        subscription_id: read_u64(&payload[24..32]),
        venue_id: read_u64(&payload[32..40]),
        instrument_id: read_u64(&payload[40..48]),
        timestamp_source,
        flags,
    })
}

fn read_u32(bytes: &[u8]) -> u32 {
    u32::from_le_bytes(bytes.try_into().expect("validated raw capture u32 slice"))
}

fn read_u64(bytes: &[u8]) -> u64 {
    u64::from_le_bytes(bytes.try_into().expect("validated raw capture u64 slice"))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{MarketDataWalReplayFilter, SegmentedMarketDataWal};
    use std::fs;
    use std::path::PathBuf;
    use std::time::{SystemTime, UNIX_EPOCH};

    struct TempRoot(PathBuf);

    impl TempRoot {
        fn new(name: &str) -> Self {
            let suffix = SystemTime::now()
                .duration_since(UNIX_EPOCH)
                .expect("system clock")
                .as_nanos();
            let path = std::env::temp_dir().join(format!("of-raw-capture-{name}-{suffix}"));
            fs::create_dir_all(&path).expect("create temp root");
            Self(path)
        }
    }

    impl Drop for TempRoot {
        fn drop(&mut self) {
            let _ = fs::remove_dir_all(&self.0);
        }
    }

    fn metadata() -> RawCaptureMetadata {
        RawCaptureMetadata {
            provider_id: 7,
            adapter_id: 11,
            connection_id: 13,
            subscription_id: 17,
            venue_id: 19,
            instrument_id: 23,
            timestamp_source: RawCaptureTimestampSource::KernelSoftware,
            flags: RawCaptureFlags::REDACTED.union(RawCaptureFlags::COMPRESSED),
        }
    }

    #[test]
    fn envelope_round_trip_preserves_metadata_and_payload() {
        let mut encoded = Vec::new();
        prepare_raw_capture_payload(metadata(), &mut encoded);
        encoded.extend_from_slice(b"native-message");
        let input = RawCaptureRecordInput::from_encoded_payload(29, 31, 37, encoded)
            .expect("valid envelope");
        assert_eq!(input.metadata(), metadata());
        assert_eq!(input.provider_sequence(), 29);
        assert_eq!(input.provider_payload(), b"native-message");
    }

    #[test]
    fn malformed_envelopes_fail_closed() {
        let mut encoded = Vec::new();
        prepare_raw_capture_payload(metadata(), &mut encoded);
        encoded[49] = 0x80;
        let error = RawCaptureRecordInput::from_encoded_payload(0, 0, 0, encoded)
            .expect_err("invalid flags");
        assert_eq!(error.error(), &RawCaptureDecodeError::InvalidFlags(0x80));
        assert_eq!(error.encoded_payload().len(), RAW_CAPTURE_HEADER_LEN);

        let error = RawCaptureRecordInput::from_encoded_payload(0, 0, 0, vec![0; 8])
            .expect_err("truncated header");
        let (cause, allocation) = error.into_parts();
        assert_eq!(cause, RawCaptureDecodeError::TruncatedHeader);
        assert_eq!(allocation, vec![0; 8]);
    }

    #[test]
    fn bounded_writer_replays_provider_evidence() {
        let root = TempRoot::new("round-trip");
        let writer = BoundedRawCaptureWriter::start(
            SegmentedMarketDataWalConfig::new(&root.0),
            BoundedMarketDataWriterConfig::new()
                .with_queue_capacity(4)
                .with_max_queued_payload_bytes(4096),
        )
        .expect("start writer");
        writer
            .producer()
            .try_capture_copy(metadata(), 41, 43, 47, b"wire-bytes")
            .expect("capture");
        let metrics = writer.shutdown().expect("shutdown");
        assert_eq!(metrics.written_records, 1);

        let wal = SegmentedMarketDataWal::open(SegmentedMarketDataWalConfig::new(&root.0))
            .expect("reopen capture");
        let mut records = Vec::new();
        wal.replay_filtered(
            MarketDataWalReplayFilter::new()
                .with_kind(Some(MarketDataWalRecordKind::RawProviderMessage)),
            &mut records,
        )
        .expect("replay");
        assert_eq!(records.len(), 1);
        let capture = RawCaptureRecord::try_from(records.pop().expect("capture record"))
            .expect("decode capture");
        assert_eq!(capture.metadata, metadata());
        assert_eq!(capture.provider_sequence, 41);
        assert_eq!(capture.ts_exchange_ns, 43);
        assert_eq!(capture.ts_recv_ns, 47);
        assert_eq!(capture.payload, b"wire-bytes");
    }

    #[test]
    fn rejection_returns_original_capture_allocation() {
        let root = TempRoot::new("too-large");
        let writer = BoundedRawCaptureWriter::start(
            SegmentedMarketDataWalConfig::new(&root.0).with_max_payload_bytes(64),
            BoundedMarketDataWriterConfig::new(),
        )
        .expect("start writer");
        let input = RawCaptureRecordInput::copy_from_slice(metadata(), 1, 2, 3, b"too-large");
        let error = writer
            .try_capture_owned(input)
            .expect_err("envelope exceeds limit");
        let returned = error.into_input();
        assert_eq!(returned.provider_payload(), b"too-large");
        assert_eq!(writer.metrics().payload_too_large_rejections, 1);
        writer.shutdown().expect("shutdown");
    }
}
