package com.orderflow.bindings;

import com.sun.jna.Library;
import com.sun.jna.Memory;
import com.sun.jna.Native;
import com.sun.jna.Pointer;
import com.sun.jna.ptr.IntByReference;
import com.sun.jna.ptr.LongByReference;
import com.sun.jna.ptr.PointerByReference;

/**
 * Generated JNA mapping for the exported Orderflow C ABI.
 *
 * <p>Generated by {@code tools/generate_binding_signatures.py}; do not edit.
 * High-level lifecycle, ownership, and error handling remain in the manual wrappers.
 */
public interface OrderflowNative extends Library {
    /** Loads the native library from a concrete path. */
    static OrderflowNative load(String path) {
        return Native.load(path, OrderflowNative.class);
    }

    /** Returns ABI version number. */
    int of_api_version();

    /** Returns static build info string. */
    String of_build_info();

    /** Returns execution ABI version number. */
    int of_execution_api_version();

    /** Inspects an execution WAL file and writes an integrity report. */
    int of_execution_wal_integrity_report(String path, OfExecutionWalIntegrityReport out_report);

    /** Inspects a segmented execution WAL root and writes an integrity report. */
    int of_execution_segmented_wal_integrity_report(String root, OfExecutionSegmentedWalIntegrityReport out_report);

    /** Inspects an execution checkpoint store root and writes an integrity report. */
    int of_execution_checkpoint_store_integrity_report(String root, OfExecutionCheckpointStoreIntegrityReport out_report);

    /** Creates a simulated execution engine instance. */
    int of_execution_engine_create(OfExecutionRouteConfig cfg, PointerByReference out_engine);

    /** Creates a simulated execution engine instance with multiple route/account/symbol configs. */
    int of_execution_engine_create_multi(OfExecutionRouteConfig[] routes, int route_count, PointerByReference out_engine);

    /** Starts an execution engine. */
    int of_execution_engine_start(Pointer engine);

    /** Stops an execution engine. */
    int of_execution_engine_stop(Pointer engine);

    /** Submits an execution order and writes events into caller-owned array. */
    int of_execution_submit_order(Pointer engine, OfExecutionOrderRequest req, OfExecutionEvent[] out_events, IntByReference inout_len);

    /** Cancels an execution order and writes events into caller-owned array. */
    int of_execution_cancel_order(Pointer engine, OfExecutionCancelRequest req, OfExecutionEvent[] out_events, IntByReference inout_len);

    /** Amends an execution order and writes events into caller-owned array. */
    int of_execution_amend_order(Pointer engine, OfExecutionAmendRequest req, OfExecutionEvent[] out_events, IntByReference inout_len);

    /** Polls execution events into caller-owned array. */
    int of_execution_poll(Pointer engine, OfExecutionEvent[] out_events, IntByReference inout_len);

    /** Gets current order state by client order id. */
    int of_execution_get_order_state(Pointer engine, String client_order_id, OfExecutionOrderState out_state);

    /** Gets execution health. */
    int of_execution_health(Pointer engine, OfExecutionHealth out_health);

    /** Gets execution metrics. */
    int of_execution_metrics(Pointer engine, OfExecutionMetrics out_metrics);

    /** Creates and starts a concurrent simulated execution engine instance. */
    int of_execution_concurrent_engine_create_multi(OfExecutionRouteConfig[] routes, int route_count, OfExecutionConcurrentConfig config, PointerByReference out_engine);

    /** Requests concurrent execution worker stop. */
    int of_execution_concurrent_stop(Pointer engine, LongByReference out_sequence);

    /** Sends a non-blocking submit command. */
    int of_execution_concurrent_submit_order(Pointer engine, OfExecutionOrderRequest req, LongByReference out_sequence);

    /** Sends a non-blocking cancel command. */
    int of_execution_concurrent_cancel_order(Pointer engine, OfExecutionCancelRequest req, LongByReference out_sequence);

    /** Sends a non-blocking amend command. */
    int of_execution_concurrent_amend_order(Pointer engine, OfExecutionAmendRequest req, LongByReference out_sequence);

    /** Sends a non-blocking poll command. */
    int of_execution_concurrent_poll(Pointer engine, LongByReference out_sequence);

    /** Attempts to receive one concurrent command report without blocking. */
    int of_execution_concurrent_try_recv_report(Pointer engine, OfExecutionCommandReport out_report, OfExecutionEvent[] out_events, IntByReference inout_len);

    /** Recovers existing roots read-only and returns allocated summary JSON. */
    int of_execution_recovery_report_json(OfExecutionRecoveryConfig config, PointerByReference out_json, IntByReference out_len);

    /** Destroys an execution engine. */
    void of_execution_engine_destroy(Pointer engine);

    /** Destroys a concurrent execution engine. */
    void of_execution_concurrent_engine_destroy(Pointer engine);

    /** Creates a deterministic TWAP parent algorithm. */
    int of_execution_twap_algo_create(OfExecutionTwapConfig config, PointerByReference out_algo);

    /** Plans the next due TWAP child without advancing parent progress. */
    int of_execution_twap_algo_plan(Pointer algo, long now_ns, String child_order_id, String client_order_id, long ts_recv_ns, OfExecutionAlgoChildPlan out_plan);

    /** Commits the currently pending child plan after accepted OMS submission. */
    int of_execution_twap_algo_commit_pending(Pointer algo);

    /** Discards the currently pending child plan after failed/abandoned submission. */
    int of_execution_twap_algo_discard_pending(Pointer algo);

    /** Records child execution progress using canonical order-status values. */
    int of_execution_twap_algo_record_execution(Pointer algo, long last_qty, long leaves_qty, int order_status);

    /** Returns the current parent execution progress. */
    int of_execution_twap_algo_progress(Pointer algo, OfExecutionAlgoProgress out_progress);

    /** Destroys a deterministic TWAP algorithm handle. */
    void of_execution_twap_algo_destroy(Pointer algo);

    /** Creates a runtime engine instance. */
    int of_engine_create(OfEngineConfig cfg, PointerByReference out_engine);

    /** Starts engine adapter/session. */
    int of_engine_start(Pointer engine);

    /** Stops engine adapter/session. */
    int of_engine_stop(Pointer engine);

    /** Subscribes to a stream kind for a symbol and optional callback delivery. */
    int of_subscribe(Pointer engine, OfSymbol symbol, int kind, OfEventCallback cb, Pointer user_data, PointerByReference out_sub);

    /** Deactivates a subscription token returned by `of_subscribe`. */
    int of_unsubscribe(Pointer sub);

    /** Unsubscribes all streams for a symbol at engine level. */
    int of_unsubscribe_symbol(Pointer engine, OfSymbol symbol);

    /** Resets per-symbol analytics/session context. */
    int of_reset_symbol_session(Pointer engine, OfSymbol symbol);

    /** Injects an external trade event into runtime processing. */
    int of_ingest_trade(Pointer engine, OfTrade trade, int quality_flags);

    /** Injects an external book event into runtime processing. */
    int of_ingest_book(Pointer engine, OfBook book, int quality_flags);

    /** Configures external-feed supervision policy. */
    int of_configure_external_feed(Pointer engine, OfExternalFeedPolicy policy);

    /** Configures an engine-owned bounded segmented market-data WAL. */
    int of_configure_market_data_wal(Pointer engine, OfMarketDataWalConfig cfg);

    /** Flushes an engine-owned market-data WAL through a durability barrier. */
    int of_flush_market_data_wal(Pointer engine);

    /** Drains, synchronizes, and shuts down engine-owned market-data persistence. */
    int of_shutdown_market_data_wal(Pointer engine);

    /** Marks external feed reconnecting/degraded state. */
    int of_external_set_reconnecting(Pointer engine, byte reconnecting);

    /** Triggers health reevaluation for stale external-feed detection. */
    int of_external_health_tick(Pointer engine);

    /** Polls adapter once and dispatches callbacks/snapshots. */
    int of_engine_poll_once(Pointer engine, int quality_flags);

    /** Sets tickbar aggregation interval for new per-symbol accumulators. */
    int of_engine_set_tickbar_interval(Pointer engine, long interval_ns);

    /** Destroys engine and releases owned resources. */
    void of_engine_destroy(Pointer engine);

    /** Returns current book snapshot JSON for `symbol`. */
    int of_get_book_snapshot(Pointer engine, OfSymbol symbol, Memory out_buf, IntByReference inout_len);

    /** Returns current book analytics snapshot JSON for `symbol`. */
    int of_get_book_analytics_snapshot(Pointer engine, OfSymbol symbol, Memory out_buf, IntByReference inout_len);

    /** Computes weighted average price for an order of `qty` by walking the book. Positive qty = buy (walks asks), negative qty = sell (walks bids). */
    int of_compute_weighted_average_price(Pointer engine, OfSymbol symbol, long qty, Memory out_buf, IntByReference inout_len);

    /** Computes depth slope (average volume decay per level) over first `levels` levels. */
    int of_compute_depth_slope(Pointer engine, OfSymbol symbol, int levels, Memory out_buf, IntByReference inout_len);

    /** Returns mid price as JSON: `{"mid": N}`, or `{}` if no book data. */
    int of_get_mid_price(Pointer engine, OfSymbol symbol, Memory out_buf, IntByReference inout_len);

    /** Returns last effective spread in bps: `{"bps": N}`. */
    int of_get_effective_spread_bps(Pointer engine, OfSymbol symbol, Memory out_buf, IntByReference inout_len);

    /** Returns average half-spread cost in bps over `window` trades: `{"bps": N}`. */
    int of_get_half_spread_cost_bps(Pointer engine, OfSymbol symbol, int window, Memory out_buf, IntByReference inout_len);

    /** Returns realised spread in bps for trade `hold_ticks` ago: `{"bps": N}`. */
    int of_get_realised_spread_bps(Pointer engine, OfSymbol symbol, int hold_ticks, Memory out_buf, IntByReference inout_len);

    /** Returns book-event analytics snapshot JSON over `window_ns` window. */
    int of_get_book_event_analytics(Pointer engine, OfSymbol symbol, long window_ns, Memory out_buf, IntByReference inout_len);

    /** Returns resiliency snapshot JSON (recovery time, depth elasticity). */
    int of_get_resiliency_snapshot(Pointer engine, OfSymbol symbol, Memory out_buf, IntByReference inout_len);

    /** Returns VPIN snapshot JSON (vpin, z-score, mean, std, toxicity). */
    int of_get_vpin_snapshot(Pointer engine, OfSymbol symbol, Memory out_buf, IntByReference inout_len);

    /** Returns Kyle's Lambda snapshot JSON (lambda, R², avg lambda). */
    int of_get_kyle_lambda_snapshot(Pointer engine, OfSymbol symbol, Memory out_buf, IntByReference inout_len);

    /** Returns Amihud illiquidity snapshot JSON. */
    int of_get_amihud_snapshot(Pointer engine, OfSymbol symbol, Memory out_buf, IntByReference inout_len);

    /** Returns CVD enhancement snapshot JSON (delta ratio, z-score, divergence). */
    int of_get_cvd_enhancement_snapshot(Pointer engine, OfSymbol symbol, Memory out_buf, IntByReference inout_len);

    /** Returns pattern detection snapshot JSON (imbalance, iceberg, hidden accumulation/distribution, session type). */
    int of_get_pattern_snapshot(Pointer engine, OfSymbol symbol, Memory out_buf, IntByReference inout_len);

    /** Returns volatility snapshot JSON (classic RV, Parkinson, Garman-Klass, Yang-Zhang). */
    int of_get_volatility_snapshot(Pointer engine, OfSymbol symbol, Memory out_buf, IntByReference inout_len);

    /** Returns microstructure noise snapshot JSON. */
    int of_get_noise_snapshot(Pointer engine, OfSymbol symbol, Memory out_buf, IntByReference inout_len);

    /** Returns Hasbrouck VAR snapshot JSON (permanent/temporary impact, information share). */
    int of_get_hasbrouck_snapshot(Pointer engine, OfSymbol symbol, Memory out_buf, IntByReference inout_len);

    /** Returns Almgren-Chriss market impact snapshot JSON. */
    int of_get_almgren_chriss_snapshot(Pointer engine, OfSymbol symbol, Memory out_buf, IntByReference inout_len);

    /** Returns spread decomposition snapshot JSON. */
    int of_get_spread_decomp_snapshot(Pointer engine, OfSymbol symbol, Memory out_buf, IntByReference inout_len);

    /** Returns ACD trade duration model snapshot JSON. */
    int of_get_acd_snapshot(Pointer engine, OfSymbol symbol, Memory out_buf, IntByReference inout_len);

    /** Returns market regime snapshot JSON. */
    int of_get_regime_snapshot(Pointer engine, OfSymbol symbol, Memory out_buf, IntByReference inout_len);

    /** Returns kinetic energy snapshot JSON. */
    int of_get_kinetic_energy_snapshot(Pointer engine, OfSymbol symbol, Memory out_buf, IntByReference inout_len);

    /** Returns dark pool analytics snapshot JSON. */
    int of_get_dark_pool_snapshot(Pointer engine, OfSymbol symbol, Memory out_buf, IntByReference inout_len);

    /** Returns options flow snapshot JSON. */
    int of_get_options_flow_snapshot(Pointer engine, OfSymbol symbol, Memory out_buf, IntByReference inout_len);

    /** Returns futures analytics snapshot JSON. */
    int of_get_futures_snapshot(Pointer engine, OfSymbol symbol, Memory out_buf, IntByReference inout_len);

    /** Returns volatility signature snapshot JSON for `symbol`. */
    int of_get_vol_signature_snapshot(Pointer engine, OfSymbol symbol, Memory out_buf, IntByReference inout_len);

    /** Returns agent type identification snapshot JSON for `symbol`. */
    int of_get_agent_type_snapshot(Pointer engine, OfSymbol symbol, Memory out_buf, IntByReference inout_len);

    /** Returns dark-lit correlation snapshot JSON for `symbol`. */
    int of_get_dark_lit_correlation_snapshot(Pointer engine, OfSymbol symbol, Memory out_buf, IntByReference inout_len);

    /** Returns institutional flow snapshot JSON for `symbol`. */
    int of_get_institutional_flow_snapshot(Pointer engine, OfSymbol symbol, Memory out_buf, IntByReference inout_len);

    /** Returns OI analysis snapshot JSON for `symbol`. */
    int of_get_oi_analysis_snapshot(Pointer engine, OfSymbol symbol, Memory out_buf, IntByReference inout_len);

    /** Returns current analytics snapshot JSON for `symbol`. */
    int of_get_analytics_snapshot(Pointer engine, OfSymbol symbol, Memory out_buf, IntByReference inout_len);

    /** Returns current derived analytics snapshot JSON for `symbol`. */
    int of_get_derived_analytics_snapshot(Pointer engine, OfSymbol symbol, Memory out_buf, IntByReference inout_len);

    /** Returns current session candle snapshot JSON for `symbol`. */
    int of_get_session_candle_snapshot(Pointer engine, OfSymbol symbol, Memory out_buf, IntByReference inout_len);

    /** Returns rolling interval candle snapshot JSON for `symbol` over `window_ns`. */
    int of_get_interval_candle_snapshot(Pointer engine, OfSymbol symbol, long window_ns, Memory out_buf, IntByReference inout_len);

    /** Returns completed bar series JSON array for `symbol`. */
    int of_get_bar_series(Pointer engine, OfSymbol symbol, Memory out_buf, IntByReference inout_len);

    /** Returns current signal snapshot JSON for `symbol`. */
    int of_get_signal_snapshot(Pointer engine, OfSymbol symbol, Memory out_buf, IntByReference inout_len);

    /** Computes LOB feature snapshot from engine book state and flow metrics. */
    int of_compute_lob_features(Pointer engine, OfSymbol symbol, double trade_imbalance, double cancel_rate, double arrival_rate, Memory out_buf, IntByReference inout_len);

    /** Override analytics thresholds and buffer sizes. Pass NULL to reset to defaults. */
    int of_engine_set_analytics_config(Pointer engine, Pointer config);

    /** Returns engine metrics JSON allocated by the library. */
    int of_get_metrics_json(Pointer engine, PointerByReference out_json, IntByReference out_len);

    /** Returns market-data persistence health JSON allocated by the library. */
    int of_get_market_data_persistence_health_json(Pointer engine, PointerByReference out_json, IntByReference out_len);

    /** Returns adapter inventory JSON allocated by the library. */
    int of_get_adapter_inventory_json(PointerByReference out_json, IntByReference out_len);

    /** Returns active adapter status JSON allocated by the library. */
    int of_get_active_adapter_status_json(Pointer engine, PointerByReference out_json, IntByReference out_len);

    /** Returns built-in signal descriptor inventory JSON allocated by the library. */
    int of_get_signal_descriptors_json(PointerByReference out_json, IntByReference out_len);

    /** Returns latest signal explanation JSON for `symbol` allocated by the library. */
    int of_get_signal_explanation_json(Pointer engine, OfSymbol symbol, PointerByReference out_json, IntByReference out_len);

    /** Returns signal metrics JSON allocated by the library. */
    int of_get_signal_metrics_json(Pointer engine, PointerByReference out_json, IntByReference out_len);

    /** Validates built-in signal configuration and returns library-allocated JSON. */
    int of_validate_signal_config_json(String signal_id, OfSignalConfigParameter[] parameters, int parameter_count, PointerByReference out_json, IntByReference out_len);

    /** Constructs a built-in signal, validates ordered replay events, and returns library-allocated JSON. */
    int of_validate_signal_replay_json(String signal_id, OfSignalConfigParameter[] parameters, int parameter_count, OfSignalValidationEvent[] events, int event_count, OfSignalValidationConfig validation_config, PointerByReference out_json, IntByReference out_len);

    /** Releases strings allocated by JSON-returning helper functions. */
    void of_string_free(Pointer p);
}
