package com.orderflow.bindings;

import java.util.List;

/** Exception raised when execution pre-trade risk rejects a command. */
public final class OrderflowRiskException extends OrderflowException {
    private final List<ExecutionEvent> events;

    /** Creates a risk exception with generated execution events. */
    public OrderflowRiskException(String message, List<ExecutionEvent> events) {
        super(message);
        this.events = events;
    }

    /** Returns native rejection events generated by the failed command. */
    public List<ExecutionEvent> events() {
        return events;
    }
}
