#!/usr/bin/env python3
"""Generate the repository-wide documentation coverage inventory.

The inventory is intentionally structural: it identifies source authorities,
public-surface candidates, and existing documentation entry points. Detailed
semantic coverage is completed progressively by subsystem.
"""

from __future__ import annotations

import argparse
import ast
import json
import re
import subprocess
try:
    import tomllib
except ModuleNotFoundError:  # pragma: no cover - exercised on Python < 3.11
    import tomli as tomllib
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT = ROOT / "docs" / "knowledge-system" / "coverage-inventory.md"

RUST_PUBLIC_RE = re.compile(
    r"^\s*pub\s+(?:(?:const|async|unsafe)\s+)*(struct|enum|trait|type|const|static|fn|mod)\s+([A-Za-z_][A-Za-z0-9_]*)"
)


@dataclass(frozen=True)
class Package:
    """Cargo package metadata needed by the inventory."""

    name: str
    version: str
    description: str
    manifest: Path


def cargo_packages() -> list[Package]:
    """Return workspace packages from Cargo's machine-readable metadata."""

    completed = subprocess.run(
        ["cargo", "metadata", "--no-deps", "--format-version", "1"],
        cwd=ROOT,
        check=True,
        capture_output=True,
        text=True,
    )
    metadata = json.loads(completed.stdout)
    return [
        Package(
            name=item["name"],
            version=item["version"],
            description=item.get("description") or "",
            manifest=Path(item["manifest_path"]),
        )
        for item in metadata["packages"]
    ]


def rust_surface(package: Package) -> tuple[int, dict[str, int]]:
    """Count candidate public Rust declarations by source file kind."""

    source_root = package.manifest.parent / "src"
    counts: dict[str, int] = {}
    total = 0
    if not source_root.exists():
        return total, counts

    for path in sorted(source_root.rglob("*.rs")):
        file_count = 0
        for line in path.read_text(encoding="utf-8").splitlines():
            match = RUST_PUBLIC_RE.match(line)
            if match:
                file_count += 1
                total += 1
        if file_count:
            counts[str(path.relative_to(ROOT))] = file_count
    return total, counts


def python_surface() -> tuple[int, int]:
    """Count public Python classes and methods in the binding package."""

    root = ROOT / "bindings" / "python" / "orderflow"
    classes = 0
    methods = 0
    for path in sorted(root.glob("*.py")):
        tree = ast.parse(path.read_text(encoding="utf-8"))
        for node in tree.body:
            if isinstance(node, ast.ClassDef) and not node.name.startswith("_"):
                classes += 1
                methods += sum(
                    isinstance(item, (ast.FunctionDef, ast.AsyncFunctionDef))
                    and not item.name.startswith("_")
                    for item in node.body
                )
    return classes, methods


def java_surface() -> int:
    """Count public Java declarations using the existing binding sources."""

    root = ROOT / "bindings" / "java" / "src" / "main" / "java"
    declaration = re.compile(r"^\s*public\s+(?:static\s+|final\s+|native\s+)*")
    return sum(
        bool(declaration.match(line))
        for path in root.rglob("*.java")
        for line in path.read_text(encoding="utf-8").splitlines()
    )


def c_surface() -> int:
    """Count C ABI symbols from the repository's canonical manifest."""

    manifest = ROOT / "bindings" / "api_manifest.toml"
    with manifest.open("rb") as handle:
        data = tomllib.load(handle)
    return len(
        {
            name
            for group in data.get("function_groups", [])
            for name in group.get("functions", [])
            if isinstance(name, str)
        }
    )


def rel(path: Path) -> str:
    """Return a repository-relative POSIX path."""

    return path.relative_to(ROOT).as_posix()


def render() -> str:
    """Render the inventory as Markdown."""

    packages = cargo_packages()
    python_classes, python_methods = python_surface()
    java_declarations = java_surface()
    c_symbols = c_surface()
    lines = [
        "# Documentation Coverage Inventory",
        "",
        "> Generated by `python3 tools/generate_docs_inventory.py`.",
        "> This inventory records structural coverage; semantic completeness is tracked per subsystem.",
        "",
        "## How to Read This Inventory",
        "",
        "A source authority is the artifact whose exact names, types, values, and compatibility behavior must be preserved. A documentation page may explain that authority, but it must not silently redefine it.",
        "",
        "Coverage states are:",
        "",
        "- `inventory`: source surface is identified.",
        "- `scaffold`: a documentation destination exists, but content is incomplete.",
        "- `documented`: concepts, reference details, examples, and failure behavior are covered.",
        "- `verified`: documentation is additionally checked by generated references, tests, or CI gates.",
        "",
        "## Workspace Packages",
        "",
        "| Package | Version | Source authority | Existing reference | Initial state |",
        "| --- | --- | --- | --- | --- |",
    ]
    references = {
        "of_core": "docs/handbook/05a-of-core-reference.md",
        "of_adapters": "docs/handbook/05b-of-adapters-reference.md",
        "of_signals": "docs/handbook/05c-of-signals-reference.md",
        "of_persist": "docs/handbook/05d-of-persist-reference.md",
        "of_runtime": "docs/handbook/05e-of-runtime-reference.md",
        "of_ffi_c": "docs/handbook/05f-of-ffi-c-reference.md",
        "of_execution_core": "docs/handbook/05g-of-execution-core-reference.md",
        "of_execution": "docs/handbook/05h-of-execution-reference.md",
        "of_execution_adapters": "docs/handbook/05i-of-execution-adapters-reference.md",
        "of_fix": "docs/handbook/05j-of-fix-reference.md",
        "of_execution_algos": "docs/handbook/05k-of-execution-algos-reference.md",
        "of_analytics": "docs/handbook/05l-of-analytics-reference.md",
        "of_persist_parquet": "docs/handbook/05m-of-persist-parquet-reference.md",
    }
    for package in packages:
        source = rel(package.manifest.parent / "src")
        reference = references.get(package.name, "-")
        lines.append(
            f"| `{package.name}` | `{package.version}` | `{source}` | `{reference}` | `inventory` |"
        )

    lines.extend(
        [
            "",
            "## Public Surface Baseline",
            "",
            "| Surface | Authority | Baseline |",
            "| --- | --- | ---: |",
            f"| Rust declaration candidates | Cargo package `src/` trees | `{sum(rust_surface(p)[0] for p in packages)}` |",
            f"| C ABI symbol references | `bindings/api_manifest.toml` | `{c_symbols}` |",
            f"| Python public classes | `bindings/python/orderflow/` | `{python_classes}` |",
            f"| Python public methods | `bindings/python/orderflow/` | `{python_methods}` |",
            f"| Java public declarations | `bindings/java/src/main/java/` | `{java_declarations}` |",
            "",
            "These counts are baselines for inventory work, not compatibility claims. Public API compatibility remains governed by the Rust declarations, C header, binding signatures, manifests, tests, and release policy.",
            "",
            "## Subsystem Work Queue",
            "",
            "| Knowledge area | Primary sources | Required coverage | State |",
            "| --- | --- | --- | --- |",
            "| Foundations | `of_core`, handbook primer | Terms, units, events, timestamps, ordering, quality flags | `scaffold` |",
            "| Architecture | Workspace manifests, runtime, diagrams | Ownership, data flow, control flow, concurrency, failure domains | `scaffold` |",
            "| Market data | `of_adapters`, provider modules | Adapter lifecycle, subscriptions, health, ordering, recovery | `scaffold` |",
            "| Analytics | `of_core`, `of_analytics` | Every metric, formula, input, output, reset, and cost | `scaffold` |",
            "| Signals | `of_signals` | Traits, modules, gating, confidence, validation | `scaffold` |",
            "| Runtime | `of_runtime` | Lifecycle, snapshots, external feed, thread-safety, metrics | `scaffold` |",
            "| Persistence | `of_persist`, `of_persist_parquet` | Formats, WAL, checkpoints, replay, retention, migration | `scaffold` |",
            "| OMS and execution | `of_execution_core`, `of_execution` | State machine, risk, routing, reconciliation, recovery | `scaffold` |",
            "| FIX and adapters | `of_fix`, `of_execution_adapters` | Codec, sessions, profiles, reports, sequence recovery | `scaffold` |",
            "| Execution algorithms | `of_execution_algos` | Inputs, scheduling, child orders, limits, determinism | `scaffold` |",
            "| Bindings | C header, Python, Java | Exact ABI, ownership, errors, threading, complete workflows | `scaffold` |",
            "| Operations | `docs/ops`, deployment files | Deployment, observability, latency, security, incident recovery | `scaffold` |",
            "",
            "## Required Completion Evidence",
            "",
            "A subsystem moves from `scaffold` to `documented` only when its pages explain the domain, enumerate public items and values, document invariants and failure behavior, and include complete examples. It moves to `verified` when examples, generated references, links, diagrams, and coverage checks run successfully in CI.",
            "",
        ]
    )

    for package in packages:
        total, files = rust_surface(package)
        if not files:
            continue
        lines.extend([f"## `{package.name}` Source Surface", "", f"Candidate public declarations: `{total}`", ""])
        lines.extend(["| Source file | Candidate declarations |", "| --- | ---: |"])
        lines.extend(f"| `{path}` | `{count}` |" for path, count in files.items())
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    """Generate or validate the inventory file."""

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    rendered = render()
    if args.check:
        existing = args.output.read_text(encoding="utf-8") if args.output.exists() else ""
        if existing != rendered:
            print(f"{rel(args.output)} is not up to date")
            return 1
        print(f"OK: {rel(args.output)} is up to date")
        return 0
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(rendered, encoding="utf-8")
    print(f"wrote {rel(args.output)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
