#!/usr/bin/env python3
"""Generate a conservative Rust constants, aliases, fields, and variant index."""

from __future__ import annotations

import argparse
import json
import re
import subprocess
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT = ROOT / "docs" / "reference" / "rust-values.md"
PUBLIC_CONST = re.compile(
    r"^\s*pub\s+(const|static)\s+([A-Za-z_][A-Za-z0-9_]*)\s*:\s*(.+?)\s*=\s*(.+?);\s*$"
)
PUBLIC_ALIAS = re.compile(
    r"^\s*pub\s+type\s+([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.+?);\s*$"
)
PUBLIC_FIELD = re.compile(r"^\s*pub\s+([A-Za-z_][A-Za-z0-9_]*)\s*:\s*(.+?)[,}]?\s*$")
ENUM_VARIANT = re.compile(r"^\s*([A-Z][A-Za-z0-9_]*)\s*(?:\([^;{}]*\)|\{[^{}]*\}|=\s*[^,]+)?\s*,?\s*$")
TYPE_DECL = re.compile(r"^\s*pub\s+(struct|enum|trait)\s+([A-Za-z_][A-Za-z0-9_]*)")


@dataclass(frozen=True)
class ValueItem:
    """One source-level value or layout member."""

    package: str
    kind: str
    owner: str
    name: str
    declaration: str
    path: str
    line: int


def packages() -> list[tuple[str, Path]]:
    """Return workspace package names and source roots."""

    result = subprocess.run(
        ["cargo", "metadata", "--no-deps", "--format-version", "1"],
        cwd=ROOT,
        check=True,
        capture_output=True,
        text=True,
    )
    return [
        (item["name"], Path(item["manifest_path"]).parent / "src")
        for item in json.loads(result.stdout)["packages"]
        if (Path(item["manifest_path"]).parent / "src").exists()
    ]


def collect() -> list[ValueItem]:
    """Collect constants, aliases, fields, and enum variants."""

    items: list[ValueItem] = []
    for package, root in packages():
        for path in sorted(root.rglob("*.rs")):
            lines = path.read_text(encoding="utf-8").splitlines()
            contexts: list[tuple[str, str, int]] = []
            depth = 0
            for index, line in enumerate(lines):
                const = PUBLIC_CONST.match(line)
                if const:
                    items.append(ValueItem(package, const.group(1), "-", const.group(2), f": {const.group(3)} = {const.group(4)}", path.relative_to(ROOT).as_posix(), index + 1))
                alias = PUBLIC_ALIAS.match(line)
                if alias:
                    items.append(ValueItem(package, "type", "-", alias.group(1), f"= {alias.group(2)}", path.relative_to(ROOT).as_posix(), index + 1))

                active = contexts[-1] if contexts else None
                if active and active[0] == "struct":
                    field = PUBLIC_FIELD.match(line)
                    if field:
                        items.append(ValueItem(package, "field", active[1], field.group(1), f": {field.group(2).rstrip(',')}", path.relative_to(ROOT).as_posix(), index + 1))
                elif active and active[0] == "enum":
                    variant = ENUM_VARIANT.match(line)
                    if variant and not line.lstrip().startswith(("///", "#[")):
                        items.append(ValueItem(package, "variant", active[1], variant.group(1), line.strip().rstrip(','), path.relative_to(ROOT).as_posix(), index + 1))

                declaration = TYPE_DECL.match(line)
                opens = line.count("{")
                closes = line.count("}")
                if declaration and opens:
                    contexts.append((declaration.group(1), declaration.group(2), depth + opens - closes))
                depth += opens - closes
                while contexts and depth < contexts[-1][2]:
                    contexts.pop()
    return items


def render(items: list[ValueItem]) -> str:
    """Render the value/layout inventory."""

    counts: dict[str, int] = {}
    for item in items:
        counts[item.kind] = counts.get(item.kind, 0) + 1
    summary = ", ".join(f"`{key}`: `{counts[key]}`" for key in sorted(counts))
    lines = [
        "# Rust Values and Layout Audit",
        "",
        "> Generated by `python3 tools/generate_rust_values.py`.",
        "> This index exposes source declarations for exact value and layout review.",
        "",
        f"Indexed values and members: `{len(items)}` ({summary})",
        "",
        "The parser is intentionally conservative. The owning source and",
        "generated Rustdoc remain authoritative for complex multiline types and",
        "conditional declarations.",
        "",
        "| Package | Kind | Owner | Name | Declared type/value | Source |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for item in items:
        declaration = item.declaration.replace("|", "\\|")
        lines.append(
            f"| `{item.package}` | `{item.kind}` | `{item.owner}` | `{item.name}` | "
            f"`{declaration}` | "
            f"[`{item.path}:{item.line}`](https://github.com/gregorian-09/orderflow/blob/main/{item.path}#L{item.line}) |"
        )
    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    """Generate or validate the Rust value/layout audit."""

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    rendered = render(collect())
    if args.check:
        existing = args.output.read_text(encoding="utf-8") if args.output.exists() else ""
        if existing != rendered:
            print(f"{args.output.relative_to(ROOT)} is not up to date")
            return 1
        print(f"OK: {args.output.relative_to(ROOT)} is up to date")
        return 0
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(rendered, encoding="utf-8")
    print(f"wrote {args.output.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
