#!/usr/bin/env python3
"""Generate a source-level Python and Java binding surface audit."""

from __future__ import annotations

import argparse
import ast
import re
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT = ROOT / "docs" / "bindings" / "surface-audit.md"
JAVA_DECLARATION = re.compile(
    r"^\s*public\s+(?:static\s+|final\s+|abstract\s+|default\s+|native\s+|synchronized\s+)*"
    r"(?P<decl>(?:class|interface|enum|record)\s+\w+|[\w<>, ?\[\]]+\s+\w+\s*(?:\(|;))"
)


@dataclass(frozen=True)
class BindingItem:
    """A binding declaration and its source location."""

    language: str
    name: str
    kind: str
    path: str
    line: int
    documented: bool


def python_items() -> list[BindingItem]:
    """Collect public Python classes and methods."""

    root = ROOT / "bindings" / "python" / "orderflow"
    items: list[BindingItem] = []
    for path in sorted(root.glob("*.py")):
        tree = ast.parse(path.read_text(encoding="utf-8"))
        for node in tree.body:
            if isinstance(node, ast.ClassDef) and not node.name.startswith("_"):
                items.append(
                    BindingItem(
                        "Python", node.name, "class", path.relative_to(ROOT).as_posix(), node.lineno, bool(ast.get_docstring(node)),
                    )
                )
                for member in node.body:
                    if isinstance(member, (ast.FunctionDef, ast.AsyncFunctionDef)) and not member.name.startswith("_"):
                        items.append(
                            BindingItem(
                                "Python", f"{node.name}.{member.name}", "method", path.relative_to(ROOT).as_posix(), member.lineno, bool(ast.get_docstring(member)),
                            )
                        )
    return items


def java_items() -> list[BindingItem]:
    """Collect public Java declarations."""

    root = ROOT / "bindings" / "java" / "src" / "main" / "java"
    items: list[BindingItem] = []
    for path in sorted(root.rglob("*.java")):
        lines = path.read_text(encoding="utf-8").splitlines()
        for index, line in enumerate(lines):
            match = JAVA_DECLARATION.match(line)
            if not match:
                continue
            previous = index - 1
            while previous >= 0 and (not lines[previous].strip() or lines[previous].strip().startswith("*")):
                previous -= 1
            documented = previous >= 0 and lines[previous].strip().endswith("*/")
            declaration = " ".join(match.group("decl").split())
            kind = "type" if re.match(r"(?:class|interface|enum|record)\s+", declaration) else "member"
            items.append(
                BindingItem(
                    "Java", declaration, kind, path.relative_to(ROOT).as_posix(), index + 1, documented,
                )
            )
    return items


def render(items: list[BindingItem]) -> str:
    """Render the binding surface audit."""

    documented = sum(item.documented for item in items)
    lines = [
        "# Binding Surface Audit",
        "",
        "> Generated by `python3 tools/generate_binding_surface.py`.",
        "> This index complements the C ABI manifest and high-level binding guides.",
        "",
        f"Declarations indexed: `{len(items)}`",
        f"Declarations with source documentation markers: `{documented}`",
        "",
        "| Language | Kind | Declaration | Source | Documentation marker |",
        "| --- | --- | --- | --- | --- |",
    ]
    for item in items:
        marker = "present" if item.documented else "review"
        lines.append(
            f"| `{item.language}` | `{item.kind}` | `{item.name}` | "
            f"[`{item.path}:{item.line}`](https://github.com/gregorian-09/orderflow/blob/main/{item.path}#L{item.line}) | `{marker}` |"
        )
    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    """Generate or validate the binding surface audit."""

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    rendered = render(python_items() + java_items())
    if args.check:
        existing = args.output.read_text(encoding="utf-8") if args.output.exists() else ""
        if existing != rendered:
            print(f"{args.output.relative_to(ROOT)} is not up to date")
            return 1
        print(f"OK: {args.output.relative_to(ROOT)} is up to date")
        return 0
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(rendered, encoding="utf-8")
    print(f"wrote {args.output.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
