#!/usr/bin/env python3
"""Generate the workspace package, feature, and dependency reference."""

from __future__ import annotations

import argparse
import json
import subprocess
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT = ROOT / "docs" / "reference" / "package-matrix.md"

HANDBOOK = {
    "of_core": "05a-of-core-reference.md",
    "of_adapters": "05b-of-adapters-reference.md",
    "of_signals": "05c-of-signals-reference.md",
    "of_persist": "05d-of-persist-reference.md",
    "of_runtime": "05e-of-runtime-reference.md",
    "of_ffi_c": "05f-of-ffi-c-reference.md",
    "of_execution_core": "05g-of-execution-core-reference.md",
    "of_execution": "05h-of-execution-reference.md",
    "of_execution_adapters": "05i-of-execution-adapters-reference.md",
    "of_fix": "05j-of-fix-reference.md",
    "of_execution_algos": "05k-of-execution-algos-reference.md",
    "of_analytics": "05l-of-analytics-reference.md",
    "of_persist_parquet": "05m-of-persist-parquet-reference.md",
}


def packages() -> list[dict]:
    """Return Cargo workspace package metadata with manifest contents."""

    result = subprocess.run(
        ["cargo", "metadata", "--no-deps", "--format-version", "1"],
        cwd=ROOT,
        check=True,
        capture_output=True,
        text=True,
    )
    packages: list[dict] = []
    for package in json.loads(result.stdout)["packages"]:
        manifest = Path(package["manifest_path"])
        with manifest.open("rb") as handle:
            cargo = tomllib.load(handle)
        packages.append({"metadata": package, "manifest": manifest, "cargo": cargo})
    return packages


def dependency_names(cargo: dict) -> list[str]:
    """Return local workspace dependency names from a manifest."""

    names: list[str] = []
    for section in ("dependencies", "dev-dependencies", "build-dependencies"):
        for name, value in cargo.get(section, {}).items():
            if isinstance(value, dict) and "path" in value and name not in names:
                names.append(name)
    return sorted(names)


def feature_lines(cargo: dict) -> list[str]:
    """Return stable feature descriptions from a manifest."""

    features = cargo.get("features", {})
    if not features:
        return ["`(none)`"]
    result: list[str] = []
    for name, values in features.items():
        if values:
            result.append(f"`{name}` = {', '.join(f'`{value}`' for value in values)}")
        else:
            result.append(f"`{name}`")
    return result


def render() -> str:
    """Render the package matrix."""

    items = packages()
    lines = [
        "# Workspace Package Matrix",
        "",
        "> Generated by `python3 tools/generate_package_matrix.py` from Cargo manifests.",
        "",
        "This page is the authoritative documentation index for package versions,",
        "workspace dependencies, feature flags, READMEs, and crate reference",
        "destinations. Cargo manifests remain the source of truth.",
        "",
        "## Package Matrix",
        "",
        "| Package | Version | Description | Local dependencies | Reference | README |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for item in items:
        metadata = item["metadata"]
        name = metadata["name"]
        manifest = item["manifest"]
        readme = manifest.parent / "README.md"
        reference = HANDBOOK.get(name)
        local_deps = dependency_names(item["cargo"])
        deps = ", ".join(f"`{dep}`" for dep in local_deps) or "`(none)`"
        reference_link = f"[handbook](../handbook/{reference})" if reference else "`example`"
        readme_link = f"[README](https://github.com/gregorian-09/orderflow/blob/main/{readme.relative_to(ROOT).as_posix()})" if readme.exists() else "`missing`"
        lines.append(f"| `{name}` | `{metadata['version']}` | {metadata.get('description') or ''} | {deps} | {reference_link} | {readme_link} |")

    lines.extend(["", "## Feature Matrix", "", "| Package | Feature | Expands to |", "| --- | --- | --- |"])
    for item in items:
        name = item["metadata"]["name"]
        for feature in feature_lines(item["cargo"]):
            if " = " in feature:
                feature_name, expansion = feature.split(" = ", 1)
            else:
                feature_name, expansion = feature, "`(empty feature)`"
            lines.append(f"| `{name}` | {feature_name} | {expansion} |")

    lines.extend(
        [
            "",
            "## Version Families",
            "",
            "- The established market-data/runtime family is published on the `0.5.x` line.",
            "- Advanced analytics, execution core, OMS helpers, FIX, execution adapters, execution algorithms, and Parquet are independent `0.1.x` crate families.",
            "- New crates must not be inferred to have the same compatibility maturity as the established runtime crates.",
            "- Existing package versions, feature defaults, dependency ranges, and public README claims must be reviewed together during release preparation.",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    """Generate or validate the package matrix."""

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    rendered = render()
    if args.check:
        existing = args.output.read_text(encoding="utf-8") if args.output.exists() else ""
        if existing != rendered:
            print(f"{args.output.relative_to(ROOT)} is not up to date")
            return 1
        print(f"OK: {args.output.relative_to(ROOT)} is up to date")
        return 0
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(rendered, encoding="utf-8")
    print(f"wrote {args.output.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
